---
title: "R Notebook v2"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

# Setup
## Load packages
```{r Setup}
library(shiny)
library(shinythemes)
library(readr)
library(stringr)
library(dplyr)
library(DT)
library(tools)
library(tidyr)
library(data.table)
```


## Load data
Load the pre-prepared dataset which has been produced for this app.
```{r Load data}
dataset_file_name <- "mye_2017_wards.RData"

load(dataset_file_name)
working_popn_set <- mye_2017_wards %>%
    ungroup() %>% 
    select(LAD18NM,WD18NM
           , Sex, Age, Count
           ,Count_in_IMD2015_decile_1
           ,Count_in_IMD2015_decile_1_to_2
           ,Count_in_IMD2015_decile_1_to_3
           , Popn_estimate_source) %>% 
    # In order to group by 'Parent' area, to group to higher level geographies, we'll add columns specifying the country (England), and Englands Parent (UK) 
    mutate(Country = "England"
           ,UK = "United Kingdom")

```

# UI and Server
## Build UI
```{r UI}
# Define UI
ui <- fluidPage(
    # App title
    titlePanel("Population", windowTitle = "Population"),
    
    # Sidebar layout with a input and output definitions
    sidebarLayout(
        
        # Inputs
        sidebarPanel(
            
            # Select variable for Sex
            selectInput(inputId = "selected_sex" 
                        ,label = "Sex"
                        ,choices = c("Persons"
                                     ,"Males"
                                     ,"Females")
                        ,selected = "Persons"
            ),
            
            # Select variable for geographical level to display values for
            selectInput(inputId = "geo_group" 
                        ,label = "Geography"
                        ,choices = c("National" = "Country"
                                     ,"Local authority" = "LAD18NM"
                                     ,"Ward" = "WD18NM"
                        )
                        ,selected = "National"
            ),
            
            
            # Select variable to choose LA
            selectInput(inputId = "selected_authority" 
                        ,label = "Local Authority"
                        ,choices = c("-- All Local Authorities --",c(levels(working_popn_set$LAD18NM))) 
                        ,selected = "Southend-on-Sea"
                        ,multiple = TRUE
            ),
            
            # Select age
            wellPanel(
                h3("Define age groups"),
                h5("Use sliders to define different age groups"),
                h6("Note: 90 = 90+"),
                sliderInput(inputId = "age_group_1"
                            ,label = "Age group 1"
                            ,min = 0
                            ,max = 90
                            ,value = c(0,4)
                            ,ticks = TRUE),
                sliderInput(inputId = "age_group_2"
                            ,label = "Age group 2"
                            ,min = 0
                            ,max = 90
                            ,value = c(5,15)
                            ,ticks = TRUE),
                sliderInput(inputId = "age_group_3"
                            ,label = "Age group 3"
                            ,min = 0
                            ,max = 90
                            ,value = c(16,64)
                            ,ticks = TRUE),
                sliderInput(inputId = "age_group_4"
                            ,label = "Age group 4"
                            ,min = 0
                            ,max = 90
                            ,value = c(65,90)
                            ,ticks = TRUE)
            )
        ),
        
        # Output:
        mainPanel(
            
            tabsetPanel(type = "tabs",
                        id = "tabsetpanel",
                        
                        tabPanel(title = "Population- Counts"
                                 ,br()
                                 ,h2("Count of estimated population")
                                 ,textOutput("source_desc") 
                                 ,br()
                                 ,DT::dataTableOutput(outputId = "popntable_count")),
                        
                        tabPanel(title = "Population - Percentages by group"
                                 ,br()
                                 ,h2("Percentage of estimated population in each age group")
                                 ,textOutput("source_desc2") 
                                 ,br()
                                 ,DT::dataTableOutput(outputId = "popntable_pct")),
                        
                        tabPanel(title = "Deprivation - Counts"
                                 ,br()
                                 ,h2("Count of population in each age group living in the 30% most deprived areas")
                                 ,textOutput("source_desc3") 
                                 ,br()
                                 ,DT::dataTableOutput(outputId = "deptable_count")),
                        
                        tabPanel(title = "Deprivation - Percentages by group"
                                 ,br()
                                 ,h2("Percentage of each age group living in the 30% most deprived areas")
                                 ,textOutput("source_desc4") 
                                 ,br()
                                 ,DT::dataTableOutput(outputId = "deptable_pct"))
            )
        )
    )
)
```


## Server
Uncomment these test parameters to run the server part independently of the UI, which can sometimes be useful for testing
```{r Test parameters}
# input <- list()
# input$geo_group <- "LAD18NM"
# input$selected_authority <-  "Southend-on-Sea"
# input$age_group_1 <- c(0,4)
# input$age_group_2 <- c(5,15)
# input$age_group_3 <- c(16,64)
# input$age_group_4 <- c(65,90)
# input$selected_sex <- "Persons"
# input$dont_filter_la <-  TRUE
```


```{r Server}
# Define server function required to create the tables
server <- function(input, output, session) {
    
    
    # Create a subset of data filtering by the users selections
    popn_selected <- reactive({
        req(input$selected_authority)        
        
        
        # If the user selects anythning other than 'Country', or 'Local Authority' + 'All local authorities', then we'll want to filter the dataset to return just a single authority. Set this flag now, which will be used in the filter later 
        dont_filter_la <- case_when(
            input$geo_group == "Country" ~ TRUE
            ,input$selected_authority == "-- All Local Authorities --" ~ TRUE
            ,TRUE ~ FALSE
        )
        
        
        # We want to display the 'Parent', so that we can for example show which LA a ward is in. This code defines what the Parent is. Later, we'll use this variable to select the appropriate column to include in the output
        parent_area <- case_when(
            input$geo_group == "Country" ~ "UK"
            ,input$geo_group == "LAD18NM" ~ "Country"
            ,input$geo_group == "WD18NM" ~ "LAD18NM"
            ,TRUE ~"ERROR")
        
        
        # I'm convinced there's a smarter way to do this, but I haven't found it yet. Later we need to calculate counts as a proportion of an areas total population. This code groups by whatever level of geography the user selects, and calculates the total population in that geography. We then join that total to the main working population dataset, giving us a 'Denoms' column, to use when working out proportions
        denoms <- working_popn_set %>%
            ungroup() %>% 
            filter(Sex == "Persons") %>%
            group_by_at(vars(input$geo_group,parent_area)) %>% 
            summarise(Area_Denom = sum(Count))
        
        working_popn_set <- working_popn_set %>% 
            left_join(denoms)
        
        
        # We're going to do some conditional logic, maths, and lable creation using the age values selected by the user. Start by creating some short aliases to make them easier to work with, ag1L = lower bound of age group 1, ag1U = upper bound
        ag1L <- input$age_group_1[1]
        ag1U <- input$age_group_1[2]
        ag2L <- input$age_group_2[1]
        ag2U <- input$age_group_2[2]
        ag3L <- input$age_group_3[1]
        ag3U <- input$age_group_3[2]
        ag4L <- input$age_group_4[1]
        ag4U <- input$age_group_4[2]
        
        
        # If the user has created overlapping ranges, so the lower bound of age group 2 is >= the upper bound of age group 1, then we'll change age group 2 to start at age group 1 upper bound +1
        if(ag2L <= ag1U){
            ag2L = ag1U +1
        }
        
        # same principle for age group 3, but this time we need to make sure it's greater than the upper bounds of both age group 1 and 2
        if(ag3L <= ag1U){
            ag3L = ag1U +1
        }
        if(ag3L <= ag2U){
            ag3L = ag2U +1
        }
        
        # and the lower bound of age group 4 must be greater than the upper bounds of age groups 1, 2 and 3        
        if(ag4L <= ag1U){
            ag4L = ag1U +1
        }
        if(ag4L <= ag2U){
            ag4L = ag2U +1
        }
        if(ag4L <= ag3U){
            ag4L = ag3U +1
        }
        
        # We want the output to have columns with names that represent the age groups the user selects using the sliders, but at this stage we don't know what's going to be selected. So, create a text description of what's been selected for age group 1 through 4, which we'll later use in the column headings
        ag1_label <- paste("a. ",ag1L," to ",ag1U)
        ag2_label <- paste("b. ",ag2L," to ",ag2U)
        ag3_label <- paste("c. ",ag3L," to ",ag3U)
        ag4_label <- paste("d. ",ag4L," to ",ag4U)
        
        
        
        
        # Now that we've added the additional pieces we need, we can start building the reactive dataframe
        popn_selected <- working_popn_set %>% 
            
            filter(Sex == input$selected_sex) %>%
            
            # Filter down to a single LA, if that's appropriate for the users selections
            filter(if(dont_filter_la == TRUE){
                LAD18NM %in% levels(working_popn_set$LAD18NM)      
            } else {
                LAD18NM %in%  input$selected_authority
            }) %>%

            
            # Add a new column categorising every observation as one of the user defined age groups, based on the slider input
            mutate(age_cat = case_when(
                between(Age,ag1L,ag1U) ~ ag1_label                
                ,between(Age,ag2L,ag2U) ~ ag2_label
                ,between(Age,ag3L,ag3U) ~ ag3_label
                ,between(Age,ag4L,ag4U) ~ ag4_label)
            )%>% 
            
            # Group by the user selected choices
            group_by_at(vars(input$geo_group,parent_area,age_cat)) %>%
            
            # Add a column containing the source, which acts as metadata showing where the data comes from
            mutate(Popn_estimate_source = as.character(Popn_estimate_source)
            ) %>% 
            
            # Calculate the summary figures
            summarise(Area_Total = unique(Area_Denom)
                      ,Count = sum(Count)
                      ,Percent_of_area_total = sum(Count)/unique(Area_Denom)
                      ,number_dec_1_to_3 = sum(Count_in_IMD2015_decile_1_to_3)
                      ,pct_dec_1_to_3=sum(Count_in_IMD2015_decile_1_to_3/sum(Count))) %>%
            
            # Make the column names more user friendly
            rename("Area" = 1
                   ,"Parent" = 2
                   ,"Age cat" = 3
                   ,"Total popn of area" = 4
                   ,"Number in selected age group" = 5
                   ,"% of area total in this group" = 6
                   ,"Number of selected age group living in IMD deciles 1-3" = 7
                   ,"% of the selected age group living in IMD deciles 1-3" = 8)
        
        
        
    })            
    
    # Create the output table to show population count
    # Spread the table to convert from long to wide
    # Note that we don't know how many columns there are going to be, that depends on the users age group choice, so we apply the formatting to columns 3:100, which effectively formats every column from 3 to the end
    output$popntable_count <- DT::renderDataTable(
        DT::datatable(data = popn_selected() %>% 
                          select("Area"
                                 ,"Parent"
                                 ,"Total popn of area"
                                 ,"Age cat"
                                 ,"Number in selected age group") %>% 
                          spread('Age cat',"Number in selected age group")
                      ,options = list(pageLength = 20)
                      ,rownames = FALSE)  %>%
            formatRound(3:100
                        ,mark = ","
                        , digits = 0)
    )
    
    # Create the output table to show percentage distribution between the age groups    
    output$popntable_pct <- DT::renderDataTable(
        DT::datatable(data = popn_selected() %>% 
                          select("Area"
                                 ,"Parent"
                                 ,"Age cat"
                                 ,"% of area total in this group")  %>% 
                          spread('Age cat',"% of area total in this group")
                      ,options = list(pageLength = 20)
                      ,rownames = FALSE) %>% 
            formatPercentage(3:100
                             , digits = 1)
    )
    
    # Create the output table to show counts of popn in the deprivation bracket
    output$deptable_count <- DT::renderDataTable(
        DT::datatable(data = popn_selected() %>% 
                          select("Area"
                                 ,"Parent"
                                 ,"Total popn of area"
                                 ,"Age cat"
                                 ,"Number of selected age group living in IMD deciles 1-3") %>% 
                          spread('Age cat',"Number of selected age group living in IMD deciles 1-3")
                      ,options = list(pageLength = 20)
                      ,rownames = FALSE)  %>% 
            formatRound(3:100
                        ,mark = ","
                        ,digits = 0)
    )
    
    
    # Create the output table to show percentage of each age group in the deprivation bracket    
    output$deptable_pct <- DT::renderDataTable(
        DT::datatable(data = popn_selected() %>% 
                          select("Area"
                                 ,"Parent"
                                 ,"Age cat"
                                 ,"% of the selected age group living in IMD deciles 1-3") %>% 
                          spread('Age cat',"% of the selected age group living in IMD deciles 1-3")
                      ,options = list(pageLength = 20)
                      ,rownames = FALSE)  %>% 
            formatPercentage(3:100
                             , digits = 1)
    )
    
    # output$deptable_pct <- DT::renderDataTable(
    #     DT::datatable(data = popn_selected()[c("Area"
    #                                            ,"Parent"
    #                                            ,"Age cat"
    #                                            ,"% of the selected age group living in IMD deciles 1-3")] %>% 
    #                       spread('Age cat',"% of the selected age group living in IMD deciles 1-3")
    #                   ,options = list(pageLength = 20)
    #                   ,rownames = FALSE)  %>% 
    #         formatPercentage(3:100
    #                          , digits = 1)
    # )
    
    # Create description of table
    output$source_desc <- renderText({
        paste(input$geo_group, " level population and deprivation. Population figures from 2017 mid year population estimate. Deprivation figures from English Indices of Deprivation 2015")
    })
    
    output$source_desc2 <- renderText({
        paste(input$geo_group, " level population and deprivation. Population figures from 2017 mid year population estimate. Deprivation figures from English Indices of Deprivation 2015")
    })
    
    output$source_desc3 <- renderText({
        paste(input$geo_group, " level population and deprivation. Population figures from 2017 mid year population estimate. Deprivation figures from English Indices of Deprivation 2015")
    })
    
    output$source_desc3 <- renderText({
        paste(input$geo_group, " level population and deprivation. Population figures from 2017 mid year population estimate. Deprivation figures from English Indices of Deprivation 2015")
    })
    
}



# Create Shiny app object
shinyApp(ui = ui, server = server)

```